/*
 * Copyright (c) 2020 Raspberry Pi (Trading) Ltd.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

// -----------------------------------------------------
// NOTE: THIS HEADER IS ALSO INCLUDED BY ASSEMBLER SO
//       SHOULD ONLY CONSIST OF PREPROCESSOR DIRECTIVES
// -----------------------------------------------------

// This header may be included by other board headers as "boards/waveshare_rp2350_pizero.h"

pico_board_cmake_set(PICO_PLATFORM, rp2350)

#ifndef _BOARDS_WAVESHARE_RP2350_PIZERO_H
#define _BOARDS_WAVESHARE_RP2350_PIZERO_H

// On some samples, the xosc can take longer to stabilize than is usual
#ifndef PICO_XOSC_STARTUP_DELAY_MULTIPLIER
#define PICO_XOSC_STARTUP_DELAY_MULTIPLIER 64
#endif

// For board detection
#define WAVESHARE_RP2350_PIZERO

// --- RP2350 VARIANT ---
// RP2350B (QFN-80)
#define PICO_RP2350A 0

// --- BOARD SPECIFIC ---

// DVI/HDMI (HSTX)
#define WAVESHARE_RP2350_PIZERO_DVI_D2P_PIN 32
#define WAVESHARE_RP2350_PIZERO_DVI_D2N_PIN 33
#define WAVESHARE_RP2350_PIZERO_DVI_D1P_PIN 34
#define WAVESHARE_RP2350_PIZERO_DVI_D1N_PIN 35
#define WAVESHARE_RP2350_PIZERO_DVI_D0P_PIN 36
#define WAVESHARE_RP2350_PIZERO_DVI_D0N_PIN 37
#define WAVESHARE_RP2350_PIZERO_DVI_CLKP_PIN 38
#define WAVESHARE_RP2350_PIZERO_DVI_CLKN_PIN 39

// HDMI DDC I2C and CEC
#define WAVESHARE_RP2350_PIZERO_DVI_SDA_PIN 44
#define WAVESHARE_RP2350_PIZERO_DVI_SCL_PIN 45
#define WAVESHARE_RP2350_PIZERO_DVI_CEC_PIN 46

// SD and SDIO
#define WAVESHARE_RP2350_PIZERO_SD_SCK_PIN 30
#define WAVESHARE_RP2350_PIZERO_SDIO_CLOCK_PIN 30

#define WAVESHARE_RP2350_PIZERO_SD_MOSI_PIN 31
#define WAVESHARE_RP2350_PIZERO_SDIO_COMMAND_PIN 31

#define WAVESHARE_RP2350_PIZERO_SD_MISO_PIN 40
#define WAVESHARE_RP2350_PIZERO_SDIO_DATA0_PIN 40

#define WAVESHARE_RP2350_PIZERO_SDIO_DATA1_PIN 41
#define WAVESHARE_RP2350_PIZERO_SDIO_DATA2_PIN 42

#define WAVESHARE_RP2350_PIZERO_SD_CS_PIN 43
#define WAVESHARE_RP2350_PIZERO_SDIO_DATA3_PIN 43

// PIO USB Host
#define WAVESHARE_RP2350_PIZERO_USB_HOST_DATA_PLUS_PIN 28
#define WAVESHARE_RP2350_PIZERO_USB_HOST_DATA_MINUS_PIN 29

// PSRAM
#define WAVESHARE_RP2350_PIZERO_PSRAM_CS_PIN 47

// --- UART ---
// UART1: TX on GPIO4, RX on GPIO5 (active on 40-pin header)
#ifndef PICO_DEFAULT_UART
#define PICO_DEFAULT_UART 1
#endif

#ifndef PICO_DEFAULT_UART_TX_PIN
#define PICO_DEFAULT_UART_TX_PIN 4
#endif

#ifndef PICO_DEFAULT_UART_RX_PIN
#define PICO_DEFAULT_UART_RX_PIN 5
#endif

// --- LED ---
// No GPIO-controlled LED on this board (LED1 is a power indicator)

// --- I2C ---
#ifndef PICO_DEFAULT_I2C
#define PICO_DEFAULT_I2C 1
#endif
#ifndef PICO_DEFAULT_I2C_SDA_PIN
#define PICO_DEFAULT_I2C_SDA_PIN 2
#endif
#ifndef PICO_DEFAULT_I2C_SCL_PIN
#define PICO_DEFAULT_I2C_SCL_PIN 3
#endif

// --- SPI ---
#ifndef PICO_DEFAULT_SPI
#define PICO_DEFAULT_SPI 1
#endif
#ifndef PICO_DEFAULT_SPI_SCK_PIN
#define PICO_DEFAULT_SPI_SCK_PIN 10
#endif
#ifndef PICO_DEFAULT_SPI_TX_PIN
#define PICO_DEFAULT_SPI_TX_PIN 11
#endif
#ifndef PICO_DEFAULT_SPI_RX_PIN
#define PICO_DEFAULT_SPI_RX_PIN 12
#endif
#ifndef PICO_DEFAULT_SPI_CSN_PIN
#define PICO_DEFAULT_SPI_CSN_PIN 9
#endif

// --- SD ---
#ifndef PICO_SD_CLK_PIN
#define PICO_SD_CLK_PIN WAVESHARE_RP2350_PIZERO_SDIO_CLOCK_PIN
#endif

#ifndef PICO_SD_CMD_PIN
#define PICO_SD_CMD_PIN WAVESHARE_RP2350_PIZERO_SDIO_COMMAND_PIN
#endif

#ifndef PICO_SD_DAT0_PIN
#define PICO_SD_DAT0_PIN WAVESHARE_RP2350_PIZERO_SDIO_DATA0_PIN
#endif

#ifndef PICO_SD_DAT_PIN_INCREMENT
#define PICO_SD_DAT_PIN_INCREMENT 1
#endif

#ifndef PICO_SD_DAT_PIN_COUNT
#define PICO_SD_DAT_PIN_COUNT 4
#endif

// --- PIO USB ---
#define PICO_DEFAULT_PIO_USB_DP_PIN WAVESHARE_RP2350_PIZERO_USB_HOST_DATA_PLUS_PIN

// --- FLASH ---
// Winbond W25Q128JVSI (16MB) flash
#define PICO_BOOT_STAGE2_CHOOSE_W25Q080 1

#ifndef PICO_FLASH_SPI_CLKDIV
#define PICO_FLASH_SPI_CLKDIV 2
#endif

pico_board_cmake_set_default(PICO_FLASH_SIZE_BYTES, (16 * 1024 * 1024))
#ifndef PICO_FLASH_SIZE_BYTES
#define PICO_FLASH_SIZE_BYTES (16 * 1024 * 1024)
#endif

pico_board_cmake_set_default(PICO_RP2350_A2_SUPPORTED, 1)
#ifndef PICO_RP2350_A2_SUPPORTED
#define PICO_RP2350_A2_SUPPORTED 1
#endif

#endif
